### ISSUE TITLE
[BUG] - Unable to run sqslite properly from a Docker container 

### ISSUE THREAD

**Issue by alan-ghelardi** [jennyEckstein/sqslite#595]
**Describe the bug**

The sqslite server cannot be exposed from within a Docker container, since it always binds to the localhost (127.0.0.1) interface.

**To Reproduce**

1. Dockerize the sqslite server. 
2. Run the Docker image as follows: `docker run -it --name sqslite --rm -p 4567:4567 <image>`. 
3. From the host, attempt to reach to the server: `curl http://localhost:4567`. 
4. See the error: Connection refused.

**Expected behavior**

The server should be able to reply properly to the aforementioned request. Exposing the server to an external network is crucial to run sqslite in a containerized CI/CD system.    

**Screenshots**

**Desktop (please complete the following information):**

- OS: [Linux (Archlinux)]
- Node Version: [14.19.3]
- Version [e.g. [2.0.1]

**Additional context**

This issue happens because nowadays sqslite always binds to the localhost interface. To work properly inside a Docker container, it should be able to bind to the 0.0.0.0 interface (exposing a --host flag seems the simplest way of achieving that). I've opened a pr to fix the issue and generated a Docker image with the fix. Compare the behavior by running `docker run -it --name sqslite --rm -p 3000:3000 alangh/sqs-lite`.

**Comment by jennyEckstein** [comment]
@alan-ghelardi Thank you for your contribution. Please allow me a couple of days to review the issue, approve the PR and make a release. Thank you in advance for your patience.

**Comment by alan-ghelardi** [comment]
@jennyEckstein take your time and thank you so much for the attention.

**Comment by jennyEckstein** [comment]
@alan-ghelardi sqslite@2.1.1 is published with the latest changes. Thank you for your contribution.

**Comment by alan-ghelardi** [comment]
Awesome. Thank you so much.
